site_title = "MyArxiv"
limit_days = 20
cache_url = "https://freeEmperor.github.io/MyArxiv/cache.json"

[[sources]]
limit = 150
category = "cs.AR"
title = "Hardware Architecture"

[[sources]]
limit = 150
category = "cs.DC"
title = "Distributed, Parallel, and Cluster Computing"

[[sources]]
limit = 150
category = "cs.AI"
title = "Artificial Intelligence"

[[sources]]
limit = 150
category = "cs.LG"
title = "Machine Learning"

[[sources]]
limit = 150
category = "cs.CL"
title = "Computation and Language"

[[sources]]
limit = 150
category = "cs.NE"
title = "Neural and Evolutionary Computing"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
